# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


workflows:
  main:
    jobs:
      - build

jobs:
  build:
    docker:
      # Be sure to upate the tag on this image to a more stable version, using latest can result in unstable builds.
      - image: microsoft/dotnet:latest
    steps:
      # Checkout the code as the first step.
      # Then simply use the dotnet container as you'd expect and run your tests
      # CircleCI will report the results back to your VCS provider.
      - checkout
      - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ~/project/App.Tests
          name: Run tests
          command: |
            dotnet test
